version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html
    depends_on:
      - php
  php:
    build: .
    container_name: my_php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html