version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html
    depends_on:
      - php
  php:
    build: .
    container_name: my_php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: